description = "Ghostty terminal configuration."
list_mode = "category"

[dest]
unix = "~/.config/ghostty"

[[files]]
source = "config.ghostty"
target = "config.ghostty"
description = "Main Ghostty configuration."

[[files]]
source = "themes/iTerm2 Solarized Light"
target = "themes/light_iTerm2 Solarized Light"
description = "Light-mode Ghostty theme with optional background image."
transforms = ["template"]

[[files]]
source = "themes/Alien Blood"
target = "themes/dark_Alien Blood"
description = "Dark-mode Ghostty theme with optional background image."
transforms = ["template"]

[[files]]
source = "themes/Atom One Light"
target = "themes/light_Atom One Light"
description = "Light-mode Ghostty theme with optional background image."
transforms = ["template"]

[[files]]
source = "themes/Github Light Default"
target = "themes/light_Github Light Default"
description = "Light-mode Ghostty theme with optional background image."
transforms = ["template"]
