# shine-dest: ~/.config/starship.toml
# Starship prompt: minimal left-prompt with git branch and status.
# Requires nerd-font: https://www.nerdfonts.com

add_newline = true
command_timeout = 500
scan_timeout = 30

format="$time$all"
#format = """
#$directory$git_branch$git_status$nodejs$rust$python$cmd_duration
#$character
#"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

#[directory]
#truncation_length = 3
#truncate_to_repo = false

[time]
disabled = false
format = '[\[ $time \]]($style) in '
time_format = '%T'
utc_time_offset = 'local'
