description = "Small shell utility commands."

[[files]]
source = "copyfile.sh"
target = "copyfile"
platforms = ["unix"]

[[files]]
source = "shine-env-export.sh"
target = "shine-env-export"
needs_source = true
platforms = ["unix"]

[[files]]
source = "shine-env-export.ps1"
target = "shine-env-export"
needs_source = true
platforms = ["windows"]

[[files]]
source = "shine-theme-sync.sh"
target = "shine-theme-sync"
needs_source = true
platforms = ["unix"]

[[files]]
source = "shine-theme-sync.ps1"
target = "shine-theme-sync"
needs_source = true
platforms = ["windows"]
