mod admin_fs;
pub mod apps;
pub mod bin_links;
#[cfg(test)]
mod bun_runtime;
pub mod colors;
pub mod commands;
pub mod completion;
pub mod config;
pub(crate) mod core_runtime;
pub mod env;
pub mod git_pull;
pub mod home;
pub mod info;
pub mod init;
pub(crate) mod install_core;
pub(crate) mod lifecycle_plan;
pub mod list;
pub mod output;
pub mod path_display;
pub mod persist;
pub mod platform;
pub(crate) mod presentation;
pub mod preset_commands;
#[cfg(test)]
mod preset_meta;
pub mod preset_validation;
pub mod presets;
pub mod privilege;
pub mod proc;
pub mod secret;
pub mod self_install;
pub mod sentinel;
pub mod serve;
pub mod shell_quote;
pub mod shells;
pub mod shim;
pub mod ssh;
pub mod state;
pub mod status;
pub mod sys;
pub mod task;
pub mod test_support;
pub mod theme;
pub mod update_check;
pub mod version;
